Task_finish_1. Badges
Dinara9595/TestGuru_rails pull request #14
Opened 2022-02-13 20:27 UTC by Dinara9595

2022-02-14 07:20 UTC, VidgarVii requested changes

2022-02-14 07:20 UTC, VidgarVii commented on app/assets/stylesheets/badges.scss
> +}
не забывай про указатель конца файла

2022-02-14 07:20 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +
лишний отступ

2022-02-14 07:20 UTC, VidgarVii commented on app/controllers/admin/badge_rules_controller.rb
> +class Admin::BadgeRulesController < Admin::BaseController
BadgeRules данные будут статичны. Для подобных данных целую таблицу выделять будет лишним. Названия правил можно просто положить, например в массив или использовать [enum](http://rusrails.ru/active-record-query-interface#perechislenie) в модели Баджей

2022-02-14 07:20 UTC, VidgarVii commented on app/models/user.rb
> +  end
вот эти все методы выше к Пользователю системы ни как не относятся. Разве в ВУЗах студенты сами принимают у себя экзамены, ставят пометки в зачётках, выдают дипломы? 
Я думаю на это есть отдельные люди. И тут нужен отдельный объект, который будет отвечать за конкретные задачи

2022-02-14 07:20 UTC, VidgarVii commented on config/routes.rb
> +  namespace :admin do
у тебя ведь есть выше объявленный namespace :admin. 
не надо каждый раз объявлять один и тот же namespace

2022-02-14 07:20 UTC, VidgarVii commented on app/models/user.rb
> +  def badge_by_test_level(level)
по ДЗ у правил есть еще параметр. Какой конкретно уровень тут проверяется? Этот уровень должен был задать администратор. Так же с категорией. 
А еще надо учесть, что  кол-во правил может быть сколько угодно большим и при этом избавиться от разбухания кода в классах и методах

2022-02-14 07:20 UTC, VidgarVii commented on app/models/user.rb
> +    add_badge(2) if array_tests.size == 1 && array_tests[0].successful?
старайся писать методы так чтобы они делали 1 вещь. Не надо их нагружать лишними задачами. С таким кодом очень тяжело работать и он подвержен багам. 
Если придётся менять название методу add_badge, то придётся править код везде

2022-02-14 07:20 UTC, VidgarVii commented on app/views/test_passages/result.html.erb
> +
1 Следи за отступами!
2 Можно обновлять эту страницу нажимая f5 и положить сервер, так как все методы несут в себе большую нагрузку. Да и вообще их стоит запускать всего 1 раз! послед завершения теста. А тест завершают не тут
3 Уже много раз говорилось, что бизнес логике в представлении не место!

2022-02-14 20:32 UTC, Dinara9595 commented on app/models/user.rb
> +  end
Имеется ввиду создать модель типа BadgeCheck чтобы туда всю логику засунуть по проверке правил выдачи бейджей? ну и разбить эти методы, чтобы они не были нагруженными и выполняли одну вещь. Я все засунула в модель User потому что у текущего пользователя дергала пройденные тесты и по ним осуществляла проверку

2022-02-14 20:48 UTC, Dinara9595 commented on app/models/user.rb
> +  def badge_by_test_level(level)
В ДЗ нет слов про параметры, либо это указано совсем не очевидно. Я поняла из комментария, что вы имеете по поводу параметров вот это: мы создаем бейдж, у которого есть name, file_name, rule, rule_parameter и вот последнее это и есть параметры правил, например, категория или уровень, или вообще остутствие параметра, если правило про прохождение теста с первой попытки.  Я правильно поняла?
И нужно как-то выстроить взаимосвязь, что если мы задаем бейджу параметр категория Backend, то только по этой категории и выдаем бейдж, что можно создать еще один бейдж с параметром категория Frontend и выдавать бейджи уже по этим обеим категориям и так далее. Я правильно поняла?


И еще из ДЗ я не понимаю вот этот пункт что здесь имеется ввиду?
"Допускается что критерии правил заданы заранее, например на уровне атрибутов модели"

2022-02-15 06:42 UTC, VidgarVii commented on app/models/user.rb
> +  def badge_by_test_level(level)
В ДЗ указано
- всех тестов определённого уровня
- всех тестов из категории Backend
- Допускается что критерии правил заданы заранее, например на уровне атрибутов модели
это всё говорит о том, что нужен параметр для правил. Чтобы задать этот уровень или категорию

2022-02-15 06:43 UTC, VidgarVii commented on app/models/user.rb
> +  def badge_by_test_level(level)
> И нужно как-то выстроить взаимосвязь, что если мы задаем бейджу параметр категория Backend, то только по этой категории и выдаем бейдж, что можно создать еще один бейдж с параметром категория Frontend и выдавать бейджи уже по этим обеим категориям и так далее. Я правильно поняла?
да

2022-02-15 06:45 UTC, VidgarVii commented on app/models/user.rb
> +  def badge_by_test_level(level)
> параметры правил, например, категория или уровень, или вообще остутствие параметра, если правило про прохождение теста спервой попытки.

Да параметр не для всех правил нужен

2022-02-15 06:51 UTC, VidgarVii commented on app/models/user.rb
> +  end
> Имеется ввиду создать модель типа BadgeCheck чтобы туда всю логику засунуть по проверке правил выдачи бейджей? ну и разбить эти методы, чтобы они не были нагруженными и выполняли одну вещь. Я все засунула в модель User потому что у текущего пользователя дергала пройденные тесты и по ним осуществляла проверку

про модель речь не идёт. Зачем вообще нужны модели? Это интруемент паттерна ActiveRecord (обязательно изучить его). Нужен только для того чтобы удобно было работать с базой данных. Мы уже проходили сервисы. Вот сервисы как раз и нужны чтобы инкапсулировать в себе бизнес логику. Совершать некие операции так сказать.

2022-02-18 07:24 UTC, VidgarVii requested changes

2022-02-18 07:24 UTC, VidgarVii commented on app/models/badge.rb
> +    self.by_level.each { |badge| badge_level_difficult << badge.rule_parameter}
чтобы получить новую коллекцию используют метод map

2022-02-18 07:24 UTC, VidgarVii commented on app/models/badge.rb
> +    self.by_level.each { |badge| badge_level_difficult << badge.rule_parameter}
self писать не принято. Тут и так понятно что обращение идёт к объекту Badge

2022-02-18 07:24 UTC, VidgarVii commented on app/models/category.rb
> +    category_name
тоже самое
тут вообще можно просто вызывать метод pluck(:name)

2022-02-18 07:24 UTC, VidgarVii commented on app/models/test.rb
> +  end
тоже самое

2022-02-18 07:24 UTC, VidgarVii commented on app/services/badge_addition_service.rb
> +
тут я вно нарушен интерфейс класса. Я думаю достаточно 1 публичного метода call для экземпляра класса

2022-02-18 07:24 UTC, VidgarVii commented on app/services/badge_addition_service.rb
> +    current_test_parameters = [@current_test.test.category.name, @current_test.test.title, level_difficulty_string(@current_test.test.level)]
по вызову методов @current_test.test... могу предположить, что в меременной @current_test явно находится не тест

2022-02-18 07:24 UTC, VidgarVii commented on app/services/badge_addition_service.rb
> +    end if total_parameters
рубокопу бы не понравилось бы такая конструкция

2022-02-18 07:24 UTC, VidgarVii commented on app/services/badge_addition_service.rb
> +  def check_by_test_level(level, user)
методы предикаты (которые возвращают только true/false) должны иметь знак вопроса в конце

2022-02-18 07:24 UTC, VidgarVii commented on app/services/badge_addition_service.rb
> +  end
в курсе по руби было задание написать модуль валидаций
и там хорошим решением являлось в цикле перебрать по очереди все валидации и по их именам, которые хранятся в массиве, поочередно вызвать каждую валидацю

здесь можно пойти таким же путем
вызывать методы проверяющие "можно ли выдавать бейдж" по именам правил, которые хранятся в каждом бейдже

таким образом можно вместо нескольких одинаковых блоков кода прийти к одному компактному циклу

здесь стоит использовать метод `select`
его можно вызвать на коллекции, в данном случае коллекции всех бейджей и для каждого бейджа по имени его правила (записанного в поле `rule` значения) вызывать соответсвующий метод проверки

в таком стиле:
```ruby
Badge.select do |badge|
  send(badge.rule ...)
end
```
такой код выберет коллекцию бейджей, для которых методы проверки вернут `true`

2022-02-18 15:02 UTC, VidgarVii requested changes

2022-02-18 15:02 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    badges.each {|badge| user.badges.push(badge)} if badges.any?
перед итерацией не обязательно проверять наличие объектов.

2022-02-18 15:02 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    badges.each {|badge| user.badges.push(badge)} if badges.any?
пробельчики наше всё. Того требует стайл гайд
{ |badge| user.badges.push(badge) }

2022-02-18 15:02 UTC, VidgarVii commented on app/models/category.rb
> +    pluck(:name)
очень сомнительная полезность метода) only_name

2022-02-18 15:02 UTC, VidgarVii commented on app/services/badge_addition_service.rb
> +      byebug
опять попал отладлочный код

2022-02-18 15:02 UTC, VidgarVii commented on app/services/badge_addition_service.rb
> +    @current_test_passage = current_test
название параметра метода не стыкуется с названием переменной

2022-02-18 15:02 UTC, VidgarVii commented on app/services/badge_addition_service.rb
> +    byebug
сколько ж вас тут byebug ов

2022-02-18 15:07 UTC, VidgarVii requested changes

2022-02-18 15:07 UTC, VidgarVii commented on app/models/badge.rb
> +  enum rule: [:by_category?, :first_try?, :by_level?]
называть правила со знаком вопроса кажется не совсем корректно.
Тут в модель просачивается application логика.
знак вопроса это соглашение для методов предикатов.

2022-02-18 15:32 UTC, merged