Task_2
Dinara9595/TestGuru_rails pull request #2
Opened 2021-12-10 20:45 UTC by Dinara9595

2021-12-11 13:15 UTC, VidgarVii requested changes

2021-12-11 13:15 UTC, VidgarVii commented on db/migrate/20211210220105_add_nul_constraint.rb
> +    change_column_null(:questions, :body, false)
Добрый вечер
Ни одно замечание не было исправлено. Как минимум можно ведь было руками протестировать своё же код?
Есть явные критические баги. Какой смысл сдавать тоже самое ДЗ если ни чего не менялось? 
Игнорирование замечаний еще хуже чем сдавать не рабочий код.
Если что-то не понятно или с чем-то не согласен обычно пишут в ЛС в слак.

2021-12-11 13:15 UTC, VidgarVii commented on db/migrate/20211210232001_change_column_default_to_answers.rb
> +    change_column_default :answers, :correct, from: true, to: false
на этом задании надо еще добавить связи м/у таблицами. 
Так как тест принадлежит определенной категории надо использовать метод references
пример

```
t.references :category, null: false, foreign_key: true
```

тут мы укажем, что поле должно быть обязательно заполнен и обеспечим ссылочную целостность данных, через внешний ключ
[внешние ключи](https://en.wikipedia.org/wiki/Foreign_key)


Тест принадлежит Категории и Автору
Тест имеет Вопросы
Вопросы имеют Ответы

2021-12-11 13:53 UTC, Dinara9595 commented on db/migrate/20211210220105_add_nul_constraint.rb
> +    change_column_null(:questions, :body, false)
Добрый вечер, я не понимаю о каких замечаниях идет речь, это же новые файлы, новый код, новая Task_2, я ее впервые отправляю на проверку. О каком том же самом ДЗ идет речь? Или идет речь о каких-то замечаниях по Task_1 ?  Но там же мы не создавали модели. А где писать в слак? Я знаю только ваш аккаунт в телеграм

2021-12-11 13:54 UTC, Dinara9595 commented on db/migrate/20211210232001_change_column_default_to_answers.rb
> +    change_column_default :answers, :correct, from: true, to: false
Хорошо, это я поправлю

2021-12-11 13:57 UTC, Dinara9595 commented on db/migrate/20211210220105_add_nul_constraint.rb
> +    change_column_null(:questions, :body, false)
https://github.com/Dinara9595/TestGuru_rails/pull/1 по Task_1 были комментарии поправить README.ms я поправила и потом только сделала слияние с main

2021-12-14 14:16 UTC, VidgarVii commented on db/migrate/20211210205623_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
лучше чтобы поле в таблице называлось author_id.
Так как по логике нам надо создать ассоциацию как автор теста
т.е. получиться
t.references :author... 
Но учти чтоб внешний ключ смотрел на таблицу юзеров
Все опции смотри тут 
https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/add_reference

2021-12-14 14:16 UTC, VidgarVii commented on db/migrate/20211210205623_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
foreign_key: { to_table: :users }

2021-12-14 14:51 UTC, merged